### ISSUE TITLE
Problem with Script

### ISSUE THREAD

**Issue by shoox8** [DanCarzano/dotfiles-awesomewm#2]
Hi guy! I´m using Parrot OS, but when I execute the script, the result is as follows:

![image](https://user-images.githubusercontent.com/56641047/162565954-a56c57dc-edcc-46dc-9da3-305111782ec6.png)

I would like that when I execute the script get the same result as your screenshot from the repo, is it possible?

**Comment by U-L-M-S** [comment]
"Currently the install script does not support the installation of .vimrc and .zshrc. These still need to be installed manually"

Did you installed oh-my-zsh ? 

Right now I'm formating my laptop and installing pop_os! as OS and I prettend to use this rice as base for my new WM (awesome).

When I'm finished I can give you a hand :)

**Comment by shoox8** [comment]
Yes, I installed oh-my-zsh. But I would like the same config of the screenshot. It would be a pleasure to have your help.

**Comment by DanCarzano** [comment]
Hi, as stated in the README, the script is not currently installing .vimrc and .zshrc. 

You will need to manually place the chrollo.zsh-theme file into your .oh-my-zsh/themes directory, and replace your .zshrc file for mine. Once that is done, restart your terminal and it should work fine

Also for the icons not showing up on your bar, you need to install font awesome 6 brands font, this should be part of the font awesome 6 free pack on their website.

**Comment by DanCarzano** [comment]
> Hi guy! I´m using Parrot OS, but when I execute the script, the result is as follows:
> 
> ![image](https://user-images.githubusercontent.com/56641047/162565954-a56c57dc-edcc-46dc-9da3-305111782ec6.png)
> 
> I would like that when I execute the script get the same result as your screenshot from the repo, is it possible?

**Comment by DanCarzano** [comment]
Closing as there hasn't been any more discussion for over a week.
